- pygoat/introduction/static/introduction/style4.css
- pygoat/introduction/templates/Lab/XSS/xss.html
Completed Refactoring, lab solution, and mitigation for XSS. Next working with SQL content.
> XSS Intro  and writeup Completed

- pygoat/introduction/templates/Lab/BrokenAccess/ba.html
- pygoat/introduction/templates/Lab/CMD/cmd.html
- pygoat/introduction/templates/Lab/CMD/cmd_lab.html
- pygoat/introduction/templates/introduction/base.html
- pygoat/introduction/urls.py
- pygoat/introduction/views.py
Added a Command injection Lab 
Updating To DO :
> Added Command Injection Lab

- pygoat/introduction/models.py
Django ignores max_length for integer fields
> Error Fixed

- pygoat/introduction/templates/Lab/insec_des/insec_des.html
> Writeup for A8

- pygoat/introduction/templates/Lab/sec_mis/sec_mis.html
- pygoat/introduction/templates/Lab/sec_mis/sec_mis_lab.html
- pygoat/introduction/templates/introduction/base.html
- pygoat/introduction/urls.py
- pygoat/introduction/views.py
> A6: Security Misconfiguration

- pygoat/Solutions/solution.md
Need to add more images to challenges involving burpsuite
> Solutions 

- pygoat/introduction/static/Lab/xss.js
- pygoat/introduction/templates/Lab/XXE/xxe_lab.html
> Fix XXE lab

- installer.sh
- uninstaller.sh
Added installer and uninstaller for pygoat. 
Tested on ubuntu
> Added installer and uninstaller

- README.md
- docs/dev_guide.md
- pygoat/Solutions/solution.md
**READY**
- Added Developer's guide.
- Added images for most challenges in solutions.md and updated solutions for a few challenges
- Changed Readme.md
> Added Developer's guide. Improved Solutions.md with all latest solutions with images. Changed Readme.md. 

- README.md
** READY **
- Changed `Readme.md` - updated installation instructions
- Added new video to Video installation Section
> Updated Readme.md installation instructions and added new installation video

- README.md
- installer.sh
- requirements.txt
- setup.py
- uninstaller.sh
Hey, I added a `setup.py` for easier installations using `pip`
This will lead to easier builds on distributions which do not use `apt` as a package manager like `Arch`, `Gentoo`, `Fedora`, etc 😄
> Added Distro independent installer and refactored scripts

- README.md
- pygoat/introduction/templates/Lab/ssrf/ssrf.html
- pygoat/introduction/templates/Lab/ssrf/ssrf_lab.html
> Dockerfile Update

- pygoat/Solutions/solution.md
**READY**
- Updated `Solutions.md` with solution for 2021-A1: Broken Access Control - Lab 2
> Added Solutions for 2021-A1: Broken Access Control - Lab 2

- pygoat/introduction/static/Lab/ssrf.css
- pygoat/introduction/static/Lab/ssrf.js
- pygoat/introduction/templates/Lab/ssrf/ssrf_discussion.html
> text areas added for code input

- pygoat/Solutions/solution.md
accesing -> accessing
acheive -> achieve
runnning -> running
> Fix typo in solution.md

- Dockerfile
- docker-compose.yml
- pygoat/Dockerfile
- pygoat/requirements.txt
Replaced Django development servers with production level `gunicorn` servers.
> Added production level servers to host pygoat

- pygoat/introduction/templates/Lab/A9/a9.html
- pygoat/introduction/templates/Lab/A9/a9_lab2.html
- pygoat/introduction/urls.py
- pygoat/introduction/views.py
> lab2 added in A6:vulnerable & outdated content

- pygoat/introduction/static/fake.txt
- pygoat/introduction/static/real.txt
- pygoat/introduction/templates/Lab_2021/A7_auth_failure/lab3.html
- pygoat/introduction/templates/Lab_2021/A8_software_and_data_integrity_failure/desc.html
- pygoat/introduction/templates/Lab_2021/A8_software_and_data_integrity_failure/lab2.html
- pygoat/introduction/templates/introduction/base.html
- pygoat/introduction/urls.py
- pygoat/introduction/views.py
- ## lab details 
- file integrity error [ XXS can be done and downloadable can be changed  using crafted URL ]
- mapped CVE
-  [CWE-494 Download of Code Without Integrity Check](https://cwe.mitre.org/data/definitions/494.html)
- [CWE-345 Insufficient Verification of Data Authenticity](https://cwe.mitre.org/data/definitions/345.html)
- [CWE-915 Improperly Controlled Modification of Dynamically-Determined Object Attributes](https://cwe.mitre.org/data/definitions/915.html)
> lab2 added in 2021:A8

- pygoat/introduction/apis.py
- pygoat/introduction/playground/A6/soln.py
- pygoat/introduction/playground/A6/utility.py
- pygoat/introduction/playground/A9/api.py
- pygoat/introduction/static/js/a6.js
- pygoat/introduction/static/js/a7.js
- pygoat/introduction/static/js/a9.js
- pygoat/introduction/templates/Lab_2021/A7_auth_failure/a7.html
- pygoat/introduction/templates/playground/A6/index.html
- pygoat/introduction/templates/playground/A7/index.html
- pygoat/introduction/templates/playground/A9/index.html
- pygoat/introduction/urls.py
- pygoat/introduction/views.py
> discussion session added in A7

- pygoat/introduction/templates/registration/login.html
> Fix UI/ register ui fix

- .github/workflows/hadolint.yml
- app.log
- introduction/forms.py
- introduction/templates/registration/register.html
- introduction/views.py
- lib/python3.10/site-packages/php_wsgi/php_app.py
> Fixes Registration form issue

- introduction/static/css/dark-theme.css
- introduction/templates/registration/login.html
Hey!
Just made few tweaks to make the dark theme better.
> Upgraded Dark Theme

- introduction/static/css/dark-theme.css
- introduction/templates/registration/register.html
There were still some issues left in #188 which have been fixed in this PR. I have verified all the pages and they theme works great now!
> Fixed Dark Theme

- Solutions/solution.md
- introduction/templates/Lab/CMD/cmd.html
- introduction/templates/Lab/CMD/cmd_lab2.html
- introduction/urls.py
- introduction/views.py
Added Command Injection Lab which demonstrates the use of eval() function in Python.
> Create: Command Injection Lab 2

- Dockerfile
- requirements.txt
The Dockerfile has been updated to resolve the build error.
> Updated dockerfile

- CHANGELOG.md
> updated changelog.md

- CHANGELOG.md
- LICENSE.md
> Added MIT License

- dockerized_labs/broken_auth_lab/Dockerfile
- dockerized_labs/broken_auth_lab/README.md
- dockerized_labs/broken_auth_lab/app.py
- dockerized_labs/broken_auth_lab/docker-compose.yml
- dockerized_labs/broken_auth_lab/requirements.txt
- dockerized_labs/broken_auth_lab/static/style.css
- dockerized_labs/broken_auth_lab/templates/base.html
- dockerized_labs/broken_auth_lab/templates/dashboard.html
- dockerized_labs/broken_auth_lab/templates/index.html
- dockerized_labs/broken_auth_lab/templates/lab.html
- dockerized_labs/broken_auth_lab/templates/reset.html
> standalone lab of Broken Authentication

- introduction/views.py
The test data has multiple admin users, so the cf lab was throwing an exception when 2 users were found.
> Fix CF lab

- dockerized_labs/crypto_failure_lab/Dockerfile
- dockerized_labs/crypto_failure_lab/README.md
- dockerized_labs/crypto_failure_lab/app.py
- dockerized_labs/crypto_failure_lab/docker-compose.yml
- dockerized_labs/crypto_failure_lab/requirements.txt
- dockerized_labs/crypto_failure_lab/static/style.css
- dockerized_labs/crypto_failure_lab/templates/base.html
- dockerized_labs/crypto_failure_lab/templates/index.html
- dockerized_labs/crypto_failure_lab/templates/lab1.html
- dockerized_labs/crypto_failure_lab/templates/lab2.html
- dockerized_labs/crypto_failure_lab/templates/lab3.html
- dockerized_labs/ssrf_lab/Dockerfile
- dockerized_labs/ssrf_lab/README.md
- dockerized_labs/ssrf_lab/app.py
- dockerized_labs/ssrf_lab/blogs/blog1.txt
- dockerized_labs/ssrf_lab/blogs/blog2.txt
- dockerized_labs/ssrf_lab/blogs/blog3.txt
- dockerized_labs/ssrf_lab/blogs/blog4.txt
- dockerized_labs/ssrf_lab/docker-compose.yml
- dockerized_labs/ssrf_lab/requirements.txt
- dockerized_labs/ssrf_lab/static/style.css
- dockerized_labs/ssrf_lab/templates/base.html
- dockerized_labs/ssrf_lab/templates/index.html
- dockerized_labs/ssrf_lab/templates/internal.html
- dockerized_labs/ssrf_lab/templates/lab1.html
- dockerized_labs/ssrf_lab/templates/lab2.html
Added two standalone labs [OWASP Top ten 2021]
- Cryptographic Failure
- SSRF (Server-Side Request Forgery)
> Added standalone labs - SSRF and Cryptographic failure 

- CHANGELOG.md
Updated Changelog for v3.0.0 pre Version
- Document refactored architecture with Flask-based microservices via Django gateway
- Challenges section details of new labs (Business Logic Flaw, Security Headers Misconfiguration, BoPLA)
- secure coding showcase
- Noted Docker build fix (Debian Buster EOL → Bookworm upgrade)
> Updated Changelog for v3.0.0 pre Version
